services:
  backend:
    build:
      context: . # project root is the build context
      dockerfile: app/Dockerfile
    image: ${DOCKERHUB_USERNAME:-local}/flask-react-postgres-backend:latest
    container_name: backend_flask_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db

  frontend:
    build: ./static
    image: ${DOCKERHUB_USERNAME:-local}/flask-react-postgres-frontend:latest
    container_name: front_end_react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: