apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # FIXED: Use your actual DockerHub image
        image: nessim28/flask-react-postgres-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/mydb"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@postgres-service:5432/mydb"
        # Optional: Remove health checks if /health endpoint doesn't exist
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20